export const GET_COMPLAINT = 'GET_COMPLAINT';
export const GET_COMPLAINT_SUCCESS = 'GET_COMPLAINT_SUCCESS';
export const GET_COMPLAINT_FAILURE = 'GET_COMPLAINT_FAILURE';

export const CREATE_COMPLAINT = 'CREATE_COMPLAINT';
export const CREATE_COMPLAINT_SUCCESS = 'CREATE_COMPLAINT_SUCCESS';
export const CREATE_COMPLAINT_FAILURE = 'CREATE_COMPLAINT_FAILURE';

export const MODIFY_COMPLAINT = 'MODIFY_COMPLAINT';
export const MODIFY_COMPLAINT_SUCCESS = 'MODIFY_COMPLAINT_SUCCESS';
export const MODIFY_COMPLAINT_FAILURE = 'MODIFY_COMPLAINT_FAILURE';
